import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Car, ChevronDown, Edit3, Hotel, Menu, Plus, Search, Utensils, X } from "lucide-react";
import { accommodationTypes, amenities, dishCategories, foodTypes, getCatalog, saveCatalog, vehicleCategories, type CatalogData, type Vehicle, type Accommodation, type FoodEstablishment, type Dish } from "../../lib/catalog";

export const Route = createFileRoute("/admin/catalog")({ component: AdminCatalog });
type Tab = "Veículos" | "Hospedagens" | "Alimentação";
const emptyVehicle: Omit<Vehicle,"id"> = { nome:"", categoria:"Económico", capacidade:4, com_motorista:false, motorista_contacto:"", preco_dia:0, regioes:[], fotos:[], estado:"Ativo", observacoes_internas:"" };
const emptyHotel: Omit<Accommodation,"id"> = { nome:"", tipo:"Hotel", regiao:"", bairro:"", preco_noite:0, comodidades:[], fotos:[], contacto:"", estado:"Ativo", observacoes_internas:"" };
const emptyFood: Omit<FoodEstablishment,"id"> = { nome:"", tipo:"Restaurante", regiao:"", bairro:"", fotos:[], contacto:"", estado:"Ativo" };

function AdminCatalog(){
 const [tab,setTab]=useState<Tab>("Veículos"); const [data,setData]=useState<CatalogData>(getCatalog()); const [search,setSearch]=useState(""); const [region,setRegion]=useState("Todas"); const [category,setCategory]=useState("Todos"); const [drawer,setDrawer]=useState(false); const [editing,setEditing]=useState<any>(null); const [menu,setMenu]=useState<string|null>(null);
 useEffect(()=>{ const fn=()=>setData(getCatalog()); window.addEventListener("catalog-updated",fn); return()=>window.removeEventListener("catalog-updated",fn)},[]);
 const regions=useMemo(()=>Array.from(new Set([...data.veiculos.flatMap(v=>v.regioes),...data.hospedagens.map(h=>h.regiao),...data.estabelecimentos.map(e=>e.regiao)].filter(Boolean))),[data]);
 const rows=useMemo(()=>{const q=search.toLowerCase(); if(tab==="Veículos") return data.veiculos.filter(v=>(!q||v.nome.toLowerCase().includes(q))&&(region==="Todas"||v.regioes.includes(region))&&(category==="Todos"||v.categoria===category)); if(tab==="Hospedagens") return data.hospedagens.filter(h=>(!q||h.nome.toLowerCase().includes(q))&&(region==="Todas"||h.regiao===region)&&(category==="Todos"||h.tipo===category)); return data.estabelecimentos.filter(e=>(!q||e.nome.toLowerCase().includes(q))&&(region==="Todas"||e.regiao===region)&&(category==="Todos"||e.tipo===category));},[data,tab,search,region,category]);
 function openNew(){setEditing(null);setDrawer(true)} function openEdit(item:any){setEditing(item);setDrawer(true)}
 function save(item:any){const key=tab==="Veículos"?"veiculos":tab==="Hospedagens"?"hospedagens":"estabelecimentos"; const list=(data as any)[key] as any[]; const next={...data,[key]:editing?list.map(x=>x.id===item.id?item:x):[...list,{...item,id:crypto.randomUUID()}]}; setData(next);saveCatalog(next);setDrawer(false)}
 function toggle(item:any){const key=tab==="Veículos"?"veiculos":tab==="Hospedagens"?"hospedagens":"estabelecimentos";const next={...data,[key]:(data as any)[key].map((x:any)=>x.id===item.id?{...x,estado:x.estado==="Ativo"?"Inativo":"Ativo"}:x)};setData(next);saveCatalog(next);setMenu(null)}
 return <div className="min-h-screen bg-[#f7f7f5] text-[#252525]"><header className="border-b border-[#e4e1db] bg-white"><div className="mx-auto flex h-16 max-w-[1450px] items-center justify-between px-5 lg:px-8"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#CD0219] text-sm font-bold text-white">CT</div><div><div className="font-semibold">Corporate Travel</div><div className="text-[11px] text-[#858078]">Painel do Administrador</div></div></div><div className="flex items-center gap-3"><span className="hidden text-xs text-[#77736d] sm:block">Administrador</span><div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#eeeae5] text-sm font-semibold">AD</div><Menu size={19} className="md:hidden"/></div></div></header>
 <main className="mx-auto max-w-[1450px] px-5 py-7 lg:px-8"><div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link to="/" className="mb-3 inline-flex items-center gap-1 text-xs font-medium text-[#77736d] hover:text-[#CD0219]"><ArrowLeft size={14}/> Voltar ao painel</Link><h1 className="text-3xl font-semibold tracking-tight">Catálogo</h1><p className="mt-1 text-sm text-[#77736d]">Base de dados usada pelos passos de transporte, hospedagem e alimentação.</p></div><button onClick={openNew} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-[#CD0219] px-4 text-sm font-semibold text-white hover:bg-[#a90115]"><Plus size={17}/> {tab==="Alimentação"?"Novo estabelecimento":"Novo item"}</button></div>
 <div className="flex overflow-x-auto border-b border-[#dedbd5]">{(["Veículos","Hospedagens","Alimentação"] as Tab[]).map(t=><button key={t} onClick={()=>{setTab(t);setCategory("Todos");setSearch("")}} className={`flex items-center gap-2 border-b-2 px-5 py-3 text-sm font-medium ${tab===t?"border-[#CD0219] text-[#CD0219]":"border-transparent text-[#77736d]"}`}>{t==="Veículos"?<Car size={16}/>:t==="Hospedagens"?<Hotel size={16}/>:<Utensils size={16}/>} {t}</button>)}</div>
 <div className="mt-5 flex flex-wrap gap-3 rounded-xl border border-[#e4e1db] bg-white p-4"><div className="relative min-w-[220px] flex-1"><Search size={16} className="absolute left-3 top-3 text-[#aaa49b]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por nome..." className="h-10 w-full rounded-lg border border-[#ddd9d3] pl-9 pr-3 text-sm outline-none focus:border-[#CD0219]"/></div><Select value={region} onChange={setRegion} options={["Todas",...regions]} label="Região"/><Select value={category} onChange={setCategory} options={["Todos",...(tab==="Veículos"?vehicleCategories:tab==="Hospedagens"?accommodationTypes:foodTypes)]} label={tab==="Veículos"?"Categoria":tab==="Hospedagens"?"Tipo":"Tipo"}/></div>
 <div className="mt-5 overflow-x-auto rounded-xl border border-[#e4e1db] bg-white"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#faf9f7] text-xs text-[#77736d]"><tr><th className="px-5 py-3 font-medium">Item</th><th className="px-4 py-3 font-medium">{tab==="Veículos"?"Categoria": "Tipo"}</th><th className="px-4 py-3 font-medium">Região</th><th className="px-4 py-3 font-medium">Preço</th><th className="px-4 py-3 font-medium">Estado</th><th className="px-4 py-3 text-right font-medium">Ações</th></tr></thead><tbody className="divide-y divide-[#eeeae5]">{rows.length?rows.map((item:any)=><tr key={item.id} className="hover:bg-[#fdfcfb]"><td className="px-5 py-3"><div className="flex items-center gap-3"><Thumb src={item.fotos?.[0]}/><div><div className="font-medium">{item.nome}</div><div className="text-[11px] text-[#8b867e]">{tab==="Veículos"?`${item.capacidade} passageiros${item.com_motorista?" · com motorista":""}`:tab==="Hospedagens"?item.bairro:item.bairro}</div></div></div></td><td className="px-4 py-3 text-[#615e58]">{item.categoria||item.tipo}</td><td className="px-4 py-3 text-[#615e58]">{item.regioes?.join(", ")||item.regiao}</td><td className="px-4 py-3 font-semibold">{(item.preco_dia??item.preco_noite)?`${(item.preco_dia??item.preco_noite).toLocaleString("pt-MZ")} MT${item.preco_dia?" / dia":" / noite"}`:"—"}</td><td className="px-4 py-3"><Status active={item.estado==="Ativo"}>{item.estado}</Status></td><td className="relative px-4 py-3 text-right"><button onClick={()=>setMenu(menu===item.id?null:item.id)} className="rounded-md border border-[#ddd9d3] px-2 py-1 text-xs">Opções <ChevronDown size={13} className="inline"/></button>{menu===item.id&&<div className="absolute right-4 top-11 z-20 w-36 rounded-lg border border-[#ddd9d3] bg-white p-1 text-left shadow-xl"><button onClick={()=>{openEdit(item);setMenu(null)}} className="flex w-full items-center gap-2 rounded px-3 py-2 text-xs hover:bg-[#f6f4f1]"><Edit3 size={13}/> Editar</button><button onClick={()=>toggle(item)} className="w-full rounded px-3 py-2 text-left text-xs hover:bg-[#f6f4f1]">{item.estado==="Ativo"?"Desativar":"Reativar"}</button>{tab==="Alimentação"&&<button onClick={()=>{setEditing({food:item});setDrawer(true);setMenu(null)}} className="w-full rounded px-3 py-2 text-left text-xs hover:bg-[#f6f4f1]">Gerir Cardápio</button>}</div>}</td></tr>):<tr><td colSpan={6} className="px-6 py-16 text-center"><div className="text-sm font-medium">Ainda não há itens que correspondam aos filtros.</div><p className="mt-1 text-xs text-[#858078]">Cadastre um item ou ajuste a pesquisa e os filtros.</p></td></tr>}</tbody></table></div>
 {tab==="Alimentação"&&<div className="mt-4 rounded-lg border border-[#e5e1db] bg-white p-4 text-xs text-[#77736d]">Um estabelecimento só aparece no wizard quando estiver <strong>Ativo</strong>, na região escolhida e tiver pelo menos um prato <strong>Disponível</strong>.</div>}
 </main>{drawer&&<Drawer tab={tab} item={editing} onClose={()=>setDrawer(false)} onSave={save}/>}</div>
}
function Select({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:readonly string[];label:string}){return <label className="flex h-10 items-center gap-2 rounded-lg border border-[#ddd9d3] px-3 text-xs text-[#77736d]">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="bg-transparent text-sm font-medium text-[#35322e] outline-none"><>{options.map(o=><option key={o}>{o}</option>)}</></select></label>}
function Thumb({src}:{src?:string}){return src?<img src={src} className="h-10 w-14 rounded-md object-cover"/>:<div className="flex h-10 w-14 items-center justify-center rounded-md bg-[#f0ede8] text-[10px] text-[#9a958d]">Sem foto</div>}
function Status({active,children}:{active:boolean;children:string}){return <span className={`rounded-full px-2.5 py-1 text-[11px] font-medium ${active?"bg-[#e8f3eb] text-[#267244]":"bg-[#f1eeeb] text-[#706b64]"}`}>{children}</span>}
function Drawer({tab,item,onClose,onSave}:{tab:Tab;item:any;onClose:()=>void;onSave:(item:any)=>void}){const [value,setValue]=useState<any>(()=>item||tab==="Veículos"?{...emptyVehicle}:tab==="Hospedagens"?{...emptyHotel}: {...emptyFood}); const [photo,setPhoto]=useState(""); const isVehicle=tab==="Veículos", isHotel=tab==="Hospedagens"; function field(k:string,v:any){setValue((x:any)=>({...x,[k]:v}))} function addPhoto(){if(photo.trim()&&(!value.fotos||value.fotos.length<(isVehicle?4:isHotel?6:4))){field("fotos",[...(value.fotos||[]),photo.trim()]);setPhoto("")}} function submit(e:any){e.preventDefault(); if(!value.nome||!value.fotos?.length){alert("Preencha o nome e adicione pelo menos 1 foto real.");return} onSave(value)} return <div className="fixed inset-0 z-50 flex justify-end bg-black/35"><form onSubmit={submit} className="h-full w-full max-w-xl overflow-y-auto bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold uppercase tracking-wide text-[#CD0219]">{item?"Editar":"Novo"} · Catálogo</div><h2 className="mt-1 text-xl font-semibold">{isVehicle?"Veículo":isHotel?"Hospedagem":"Estabelecimento"}</h2></div><button type="button" onClick={onClose}><X size={20}/></button></div>{isVehicle?<VehicleForm v={value} field={field}/>:isHotel?<HotelForm v={value} field={field}/>:<FoodForm v={value} field={field}/>}<div className="mt-6"><label className="text-xs font-medium">Fotos ({value.fotos?.length||0})</label><div className="mt-2 flex gap-2"><input value={photo} onChange={e=>setPhoto(e.target.value)} placeholder="URL da foto real" className="h-10 flex-1 rounded-lg border border-[#ddd9d3] px-3 text-sm"/><button type="button" onClick={addPhoto} className="rounded-lg border px-3 text-sm">Adicionar</button></div><div className="mt-3 grid grid-cols-4 gap-2">{(value.fotos||[]).map((p:string)=><img key={p} src={p} className="h-16 w-full rounded-md object-cover"/>)}</div></div>{(isVehicle||isHotel)&&<label className="mt-5 block text-xs font-medium">Observações internas<textarea value={value.observacoes_internas} onChange={e=>field("observacoes_internas",e.target.value)} className="mt-1.5 min-h-20 w-full rounded-lg border border-[#ddd9d3] p-3 text-sm"/></label>}<div className="mt-7 flex justify-end gap-2 border-t pt-5"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Cancelar</button><button className="rounded-lg bg-[#CD0219] px-5 py-2 text-sm font-semibold text-white">Guardar</button></div></form></div>}
function VehicleForm({v,field}:{v:any;field:(k:string,v:any)=>void}){return <div className="mt-6 space-y-4"><Input label="Nome/modelo" value={v.nome} onChange={x=>field("nome",x)}/><div className="grid grid-cols-2 gap-3"><Input label="Capacidade de passageiros" type="number" value={v.capacidade} onChange={x=>field("capacidade",Number(x))}/><Select value={v.categoria} onChange={x=>field("categoria",x)} options={vehicleCategories} label="Categoria"/></div><div className="flex items-center gap-2"><input type="checkbox" checked={v.com_motorista} onChange={e=>field("com_motorista",e.target.checked)}/><span className="text-sm">Com motorista</span></div>{v.com_motorista&&<Input label="Nome/contacto do motorista · interno" value={v.motorista_contacto} onChange={x=>field("motorista_contacto",x)}/>}<Input label="Preço por dia (MT)" type="number" value={v.preco_dia} onChange={x=>field("preco_dia",Number(x))}/><Input label="Regiões/cidades · separadas por vírgula" value={v.regioes.join(", ")} onChange={x=>field("regioes",x.split(",").map((r:string)=>r.trim()).filter(Boolean))}/><Select value={v.estado} onChange={x=>field("estado",x)} options={["Ativo","Inativo"]} label="Estado"/></div>}
function HotelForm({v,field}:{v:any;field:(k:string,v:any)=>void}){return <div className="mt-6 space-y-4"><Input label="Nome do estabelecimento" value={v.nome} onChange={x=>field("nome",x)}/><Select value={v.tipo} onChange={x=>field("tipo",x)} options={accommodationTypes} label="Tipo"/><div className="grid grid-cols-2 gap-3"><Input label="Região/cidade" value={v.regiao} onChange={x=>field("regiao",x)}/><Input label="Bairro" value={v.bairro} onChange={x=>field("bairro",x)}/></div><Input label="Preço por noite (MT)" type="number" value={v.preco_noite} onChange={x=>field("preco_noite",Number(x))}/><div><div className="mb-2 text-xs font-medium">Comodidades</div><div className="grid grid-cols-2 gap-2">{amenities.map(a=><label key={a} className="text-xs"><input type="checkbox" checked={v.comodidades.includes(a)} onChange={e=>field("comodidades",e.target.checked?[...v.comodidades,a]:v.comodidades.filter((x:string)=>x!==a))}/> {a}</label>)}</div></div><Input label="Contacto · interno" value={v.contacto} onChange={x=>field("contacto",x)}/><Select value={v.estado} onChange={x=>field("estado",x)} options={["Ativo","Inativo"]} label="Estado"/></div>}
function FoodForm({v,field}:{v:any;field:(k:string,v:any)=>void}){return <div className="mt-6 space-y-4"><Input label="Nome do estabelecimento" value={v.nome} onChange={x=>field("nome",x)}/><Select value={v.tipo} onChange={x=>field("tipo",x)} options={foodTypes} label="Tipo"/><div className="grid grid-cols-2 gap-3"><Input label="Região/cidade" value={v.regiao} onChange={x=>field("regiao",x)}/><Input label="Bairro" value={v.bairro} onChange={x=>field("bairro",x)}/></div><Input label="Contacto · interno" value={v.contacto} onChange={x=>field("contacto",x)}/><Select value={v.estado} onChange={x=>field("estado",x)} options={["Ativo","Inativo"]} label="Estado"/></div>}
function Input({label,value,onChange,type="text"}:{label:string;value:any;onChange:(x:string)=>void;type?:string}){return <label className="block text-xs font-medium">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border border-[#ddd9d3] px-3 text-sm outline-none focus:border-[#CD0219]"/></label>}
