import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowLeft, GripVertical, Plus, Trash2 } from "lucide-react";
import { dishCategories, getCatalog, saveCatalog, type Dish } from "../../lib/catalog";

export const Route = createFileRoute("/admin/catalog-cardapio")({ component: CatalogMenu });

function CatalogMenu(){
 const [data,setData]=useState(getCatalog()); const [selected,setSelected]=useState(data.estabelecimentos[0]?.id||""); const [editing,setEditing]=useState<Dish|null>(null);
 const establishment=data.estabelecimentos.find(e=>e.id===selected); const dishes=data.pratos.filter(p=>p.estabelecimento_id===selected).sort((a,b)=>a.ordem-b.ordem);
 function save(d:Dish){const next={...data,pratos:editing?data.pratos.map(x=>x.id===d.id?d:x):[...data.pratos,{...d,id:crypto.randomUUID()}]};setData(next);saveCatalog(next);setEditing(null)}
 function toggle(d:Dish){const next={...data,pratos:data.pratos.map(x=>x.id===d.id?{...x,estado:x.estado==="Disponível"?"Indisponível":"Disponível"}:x)};setData(next);saveCatalog(next)}
 return <div className="min-h-screen bg-[#f7f7f5] text-[#252525]"><header className="border-b bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><div><div className="font-semibold">Corporate Travel</div><div className="text-[11px] text-[#817d76]">Gestão de Cardápio</div></div><Link to="/admin/catalog" className="inline-flex items-center gap-2 text-sm text-[#77736d]"><ArrowLeft size={15}/> Voltar ao catálogo</Link></div></header><main className="mx-auto max-w-6xl px-5 py-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-semibold">Cardápio</h1><p className="mt-1 text-sm text-[#77736d]">Organize os pratos por categoria e ordem de exibição.</p></div><button onClick={()=>setEditing({id:"",estabelecimento_id:selected,nome:"",categoria_prato:"Prato principal",descricao:"",preco:0,foto:"",ordem:dishes.length+1,estado:"Disponível"})} disabled={!selected} className="inline-flex items-center gap-2 rounded-lg bg-[#CD0219] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40"><Plus size={16}/> Novo prato</button></div><div className="mt-6 rounded-xl border bg-white p-4"><label className="text-xs font-medium text-[#77736d]">Estabelecimento<select value={selected} onChange={e=>setSelected(e.target.value)} className="mt-1 block h-10 w-full max-w-lg rounded-lg border px-3 text-sm">{data.estabelecimentos.map(e=><option value={e.id} key={e.id}>{e.nome} · {e.tipo}</option>)}</select></label></div>{establishment&&<div className="mt-5 rounded-xl border bg-white p-5"><div className="mb-5"><div className="font-semibold">{establishment.nome}</div><div className="text-xs text-[#817d76]">{establishment.regiao} · {establishment.bairro}</div></div>{dishCategories.map(cat=>{const list=dishes.filter(d=>d.categoria_prato===cat);return <section key={cat} className="mb-6 last:mb-0"><div className="border-b pb-2 text-xs font-semibold uppercase tracking-wide text-[#77736d]">{cat} · {list.length}</div>{list.length?list.map(d=><div key={d.id} className="flex items-center gap-3 border-b py-3 last:border-0"><GripVertical size={16} className="text-[#aaa49b]"/><img src={d.foto||""} className={`h-12 w-16 rounded-md object-cover ${d.foto?"":"hidden"}`}/><div className="min-w-0 flex-1"><div className="text-sm font-medium">{d.nome}</div><div className="truncate text-xs text-[#817d76]">{d.descricao||"Sem descrição"}</div></div><div className="text-sm font-semibold">{d.preco.toLocaleString("pt-MZ")} MT</div><button onClick={()=>toggle(d)} className="rounded-full bg-[#f1eeeb] px-2.5 py-1 text-[11px]">{d.estado}</button><button onClick={()=>setEditing(d)} className="text-xs font-semibold text-[#CD0219]">Editar</button></div>):<div className="py-3 text-xs text-[#aaa49b]">Sem pratos nesta categoria.</div>}</section>})}</div>}{editing&&<DishDrawer dish={editing} onClose={()=>setEditing(null)} onSave={save}/>}</main></div>
}
function DishDrawer({dish,onClose,onSave}:{dish:Dish;onClose:()=>void;onSave:(d:Dish)=>void}){const [v,setV]=useState(dish);const f=(k:keyof Dish,x:any)=>setV({...v,[k]:x});return <div className="fixed inset-0 z-50 flex justify-end bg-black/35"><form onSubmit={e=>{e.preventDefault();if(!v.nome||v.preco<0)return alert("Informe o nome e um preço válido.");onSave(v)}} className="h-full w-full max-w-md overflow-y-auto bg-white p-6"><div className="flex justify-between"><div><div className="text-xs font-semibold uppercase text-[#CD0219]">Cardápio</div><h2 className="mt-1 text-xl font-semibold">{dish.id?"Editar prato":"Novo prato"}</h2></div><button type="button" onClick={onClose}>Fechar</button></div><div className="mt-6 space-y-4"><Input label="Nome do prato" value={v.nome} onChange={x=>f("nome",x)}/><label className="block text-xs font-medium">Categoria<select value={v.categoria_prato} onChange={e=>f("categoria_prato",e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border px-3">{dishCategories.map(c=><option key={c}>{c}</option>)}</select></label><Input label="Preço (MT)" type="number" value={v.preco} onChange={x=>f("preco",Number(x))}/><label className="block text-xs font-medium">Descrição<textarea value={v.descricao} onChange={e=>f("descricao",e.target.value)} className="mt-1.5 min-h-20 w-full rounded-lg border p-3 text-sm"/></label><Input label="URL da foto · opcional" value={v.foto} onChange={x=>f("foto",x)}/><Input label="Ordem" type="number" value={v.ordem} onChange={x=>f("ordem",Number(x))}/><label className="block text-xs font-medium">Estado<select value={v.estado} onChange={e=>f("estado",e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border px-3"><option>Disponível</option><option>Indisponível</option></select></label></div><div className="mt-7 flex justify-end gap-2 border-t pt-5"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm">Cancelar</button><button className="rounded-lg bg-[#CD0219] px-5 py-2 text-sm font-semibold text-white">Guardar</button></div></form></div>}
function Input({label,value,onChange,type="text"}:{label:string;value:any;onChange:(v:string)=>void;type?:string}){return <label className="block text-xs font-medium">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1.5 h-10 w-full rounded-lg border px-3 text-sm"/></label>}
